# Generated by Django 3.2.8 on 2021-10-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('price', models.FloatField()),
                ('details', models.CharField(max_length=1000)),
                ('viewCount', models.IntegerField(default=0)),
                ('image', models.ImageField(default='default.jpg', upload_to='product/')),
            ],
        ),
    ]
